### ISSUE TITLE
It's still a bit Christmassy in here.

### ISSUE THREAD

**Issue by davidblurton** [aranja/aranja.com#8]
Perhaps we should limit the number of posts displayed from Facebook and start making posts more frequently :)

**Comment by thorsteinsson** [comment]
I recently increased the number because the games still work (click a game to play it). We should definitely add more posts though.

**Comment by davidblurton** [comment]
It's not obvious that you can click through and play the games - we should make more of that.

**Comment by thorsteinsson** [comment]
Yeah, we could even have a separate section where we link to our best games.

**Comment by davidblurton** [comment]
I like the idea of having the games in a case study. It's would still be weird if it was our only case study, given that it's May.

**Comment by thorsteinsson** [comment]
Not a problem anymore :smile:
